services:
    db:
      container_name: postgresdb
      image: postgres
      #restart: always
      volumes:
        - ./db/postgres/pgdata:/var/lib/postgresql/data
        - ./db/postgres/backps:/backups
      ports: 
        - 5432:5432
      environment:
        - LC_ALL=C.UTF-8
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${DB_PRUEBA}
      networks: 
        net1:         
          ipv4_address: 10.10.254.2
  
    pgadmin4:
      container_name: pgadmin4
      image: dpage/pgadmin4
      ports: 
        - 8080:80
      environment:
        - LC_ALL=C.UTF-8
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      volumes:
        - ./db/postgres/pgadmin//var/lib/pgadmin/
      networks: 
        net1:         
          ipv4_address: 10.10.254.3
  
networks:
  net1:
     driver: bridge
     ipam:
         config:
             - subnet: 10.10.254.0/29