version: '3.5'

services:
    mariadb:
        container_name: db
        image: mariadb:latest
        restart: unless-stopped
        volumes:
            - mariadb:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        networks: 
            docker_net:         
              ipv4_address: 10.10.255.2

    phpmyadmin:
        container_name: phpmyadmin
        restart: unless-stopped
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8000:80
        environment:
             PMA_ARBITRARY: 1
             PMA_HOST: mariadb
             PMA_PORT: 3306
        depends_on:
            - mariadb
        networks: 
            docker_net:         
              ipv4_address: 10.10.255.3
networks:
  docker_net:
     driver: bridge
     ipam:
         config:
             - subnet: 10.10.255.0/29

volumes:
   mariadb:
