---
services:
    mariadb:
        container_name: db
        #restart: always
        image: mariadb:latest
        restart: always
        volumes:
            - ./db/mariadb/mariadb-data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MARIADBPASSWORD}
            MYSQL_DATABASE: ${DB_PRUEBA}
        networks: 
            docker_net:         
              ipv4_address: 10.10.255.2

    phpmyadmin:
        container_name: admin
        restart: always
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8000:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mariadb
        depends_on:
            - mariadb
        networks: 
            docker_net:         
              ipv4_address: 10.10.255.3
networks:
  docker_net:
     driver: bridge
     ipam:
         config:
             - subnet: 10.10.255.0/29
...